// This file is generated by `npm run registry:shaders`.
import type { ComponentType } from "react";

import shaderExample0 from "./default/examples/shaders/blinds-demo";
import shaderExample1 from "./default/examples/shaders/grainient-demo";
import shaderExample2 from "./default/examples/shaders/light-rays-demo";

export const ShaderIndex: Record<string, { component: ComponentType }> = {
  "blinds-demo": { component: shaderExample0 },
  "grainient-demo": { component: shaderExample1 },
  "light-rays-demo": { component: shaderExample2 },
};
