// This file is generated by `npm run registry:shaders`.
import type { ComponentType } from "react";

import shaderExample0 from "./default/examples/shaders/blinds-demo";
import shaderExample1 from "./default/examples/shaders/dithering-demo";
import shaderExample2 from "./default/examples/shaders/grainient-demo";
import shaderExample3 from "./default/examples/shaders/grid-distortion-demo";
import shaderExample4 from "./default/examples/shaders/light-rays-demo";
import shaderExample5 from "./default/examples/shaders/side-rays-demo";

export const ShaderIndex: Record<string, { component: ComponentType }> = {
  "blinds-demo": { component: shaderExample0 },
  "dithering-demo": { component: shaderExample1 },
  "grainient-demo": { component: shaderExample2 },
  "grid-distortion-demo": { component: shaderExample3 },
  "light-rays-demo": { component: shaderExample4 },
  "side-rays-demo": { component: shaderExample5 },
};
