// This file is generated by `npm run registry:animated`.
import type { ComponentType } from "react";

import animatedExample0 from "./default/examples/animated/action-swap-demo";
import animatedExample1 from "./default/examples/animated/bouncy-accordion-demo";
import animatedExample2 from "./default/examples/animated/chromatic-text-reveal-demo";
import animatedExample3 from "./default/examples/animated/dock-demo";
import animatedExample4 from "./default/examples/animated/magnetic-demo";
import animatedExample5 from "./default/examples/animated/marquee-demo";
import animatedExample6 from "./default/examples/animated/number-ticker-demo";
import animatedExample7 from "./default/examples/animated/shared-layout-bg-demo";
import animatedExample8 from "./default/examples/animated/text-reveal-demo";
import animatedExample9 from "./default/examples/animated/text-shimmer-demo";
import animatedExample10 from "./default/examples/animated/tilt-card-demo";

export const AnimatedIndex: Record<string, { component: ComponentType }> = {
  "action-swap-demo": { component: animatedExample0 },
  "bouncy-accordion-demo": { component: animatedExample1 },
  "chromatic-text-reveal-demo": { component: animatedExample2 },
  "dock-demo": { component: animatedExample3 },
  "magnetic-demo": { component: animatedExample4 },
  "marquee-demo": { component: animatedExample5 },
  "number-ticker-demo": { component: animatedExample6 },
  "shared-layout-bg-demo": { component: animatedExample7 },
  "text-reveal-demo": { component: animatedExample8 },
  "text-shimmer-demo": { component: animatedExample9 },
  "tilt-card-demo": { component: animatedExample10 },
};
